### PR TITLE
Sync proof of concept, repository trait unravelling, repository collection, line ending normalisation

### PR DESCRIPTION
**Pull request by chris-morgan**

### CODE REVIEW

**Comment by chris-morgan** [comment]
Blech, force pushed to run cargo fmt. Using it never fails to remind me why I hate every code autoformatter I’ve seen: they never understand context, and will break lines in the middle of established patterns that *don’t* have broken lines, in order to maintain a foolish consistency. (Worst part is that the extra lines it broke—half the `repositories.insert(…)` lines—weren’t even quite 100 characters long, which is supposed to be the limit; no idea why it did it earlier.)

**Comment by wlthomson** [comment]
@chris-morgan Great! Thanks for this. 

> Blech, force pushed to run cargo fmt. Using it never fails to remind me why I hate every code autoformatter I’ve seen: they never understand context, and will break lines in the middle of established patterns that _don’t_ have broken lines, in order to maintain a foolish consistency. (Worst part is that the extra lines it broke—half the `repositories.insert(…)` lines—weren’t even quite 100 characters long, which is supposed to be the limit; no idea why it did it earlier.)

Oops, and it gets worse (https://github.com/openmsupply/remote-server/issues/210).

To other sussolers, if context for any changes isn't clear, CM has added commit descriptions which are really helpful. This project is no longer my baby, feel free to add reviews and request changes (I won't merge for a while).

File: Cargo.toml [hunk 1]
```diff
@@ -12,9 +12,10 @@ path = "src/main.rs"
 name = "remote_server"
 
 [dependencies]
+anymap = "0.12"
 actix-cors = "0.5.4"
 actix-rt = "1.1.0"
-actix-web = "3.3.2"
+actix-web = "3.3.2" # When updating this to 4 (when it comes out), the tokio dependency will need to be bumped to at least 1.3.
```
Comment (wlthomson) [inline Cargo.toml:18]: Learned the hard way by following `zero2production` (uses v4 beta), a nice days work lost!

**Review by wlthomson — COMMENTED** [review]
Will wait to approve until I've had a bit more of a play with some of the tokio stuff here, but all looks pretty good to me!

File: tests/graphql.rs [hunk 2]
```diff
@@ -1,63 +1,61 @@
...
-}
+#![allow(where_clauses_object_safety)]
+
+mod mocks;
+
+use remote_server::database;
+use remote_server::server;
+
+#[cfg(not(feature = "mock"))]
+compile_error!("Please run tests with --features=mock");
```
[the remark this answers is not in the document]
Comment (chris-morgan) [reply tests/graphql.rs:9]: As a matter of fact, I did it this way here because the tests will fail to compile anyway, since the pgsqlx and mock `new` methods take different arguments, but in a more obscure way; this way, you get a compilation error that tells you want to do to fix it.

(Note also the reason I made it a feature is because while *internal* tests—`#[test]` inside the src tree—would work with `cfg(test)`, external tests—`tests/*.rs`—get compiled against the regular crate not in test mode.)

[the remark this answers is not in the document]
Comment (wlthomson) [reply tests/graphql.rs:9]: Ah yup, makes sense to me. Not particularly scalable (as I think you have already mentioned), but a nice pattern for this use-case!
