### ISSUE TITLE
Fix compilation error with async-graphl version

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#771]
Had compilation errors when cargo chooses to use async graphql 2.11.1, after removing lock file compiles with 2.11.3 but having duplicate type error panics.
