### PR TITLE
771 fix compilation error with async graphql versioin

### LINKED ISSUE #771: Fix compilation error with async-graphl version
Had compilation errors when cargo chooses to use async graphql 2.11.1, after removing lock file compiles with 2.11.3 but having duplicate type error panics.

### PR DESCRIPTION
**Pull request by andreievg**
closes #771

### CODE REVIEW

**Review by clemens-msupply — APPROVED** [review]
Cool how did you find these? have they been errors?

**Comment by andreievg** [comment]
> Cool how did you find these? have they been errors?

Yep I was getting compilation errors when async-graphql was 2.11.1 (set in previous lock file), when i changed to 2.11.3 i started getting panics of duplicated types.

I also tried 2.9.8, was getting compilation errors
